version: '3.1'
services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - app_db:/data/db

  app:
    build: .
    restart: always
    pull_policy: build
    ports:
      - 8080:8080
    depends_on:
      - mongo
    env_file:
      - .env.docker

volumes:
  app_db:
